image: python:3.12

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

stages:
  - build
  - test
  - doc
  - deploy

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


build-job:
  stage: build
  script:
    - pip install -q build[virtualenv]
    - python -m build
  artifacts:
    paths:
      - dist/*.whl

pages:
  stage: doc
  script:
    - pip install -e  .[doc]
    - sphinx-apidoc -M -f -o doc/source/generated --implicit-namespaces lis2
    - sphinx-build -M html docs/source/ docs/build/
    - cp -r ./docs/build/html public
  pages: true
  artifacts:
    paths:
      - public
  publish: public/html

unit-test-job:
  stage: test
  script:
    - pip install pytest pytest-cov coverage
    - pip install -e .
    - pytest

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
