name: deepfilaments_gpu
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - astropy
  - cudatoolkit=11.1
  - h5py
  - scipy
  - matplotlib
  - python>=3.1
  - pytorch
  - scikit-image
  - pandas
  - reproject
  - seaborn
  - openpyxl
  - numba
  - tqdm
  - mlflow
  - wandb

  # code checks
  - black
  - flake8
  - flake8-docstrings
  - isort # check that imports are in the right order
  - pre-commit
  - pytest
  - pytest-cov
