output_dir: ./
run_name: run
epoch: 50
model:
  type: unet
  name: unet2D_pe_alt
  in_channels: 1
  out_channels: 1
  features: 64
  dimension: 2
  num_blocks: 5
optimizer:
  type: Adam
  lr: 0.001
scheduler:
  type: MultiStepLR
  milestones: [10, 20, 30, 40, 50, 60, 70, 80, 90]
  gamma: 0.1
dataset:
  type: FilamentsDataset
  dataset_path: /mnt/data/WORK/BigSF/data/bigdata/fold_0_train.h5
  learning_mode: conservative
  data_augmentation: noise
  normalization_mode: test
  missingmap: True
  input_data_noise: 1.
  output_data_noise: 1.
  toEncode: ['positions']
