kfold:
  dataset_path: /mnt/data/WORK/BigSF/Toolbox/PNRIA/output_new_short/patches.h5
  k: 10
  k_train: 8
  indices_path: /mnt/data/WORK/BigSF/Toolbox/PNRIA/output_new_short/indices.pkl
  save_indices: True
trainset:
  type: KFoldsFilamentsDataset
  dataset_path: /mnt/data/WORK/BigSF/Toolbox/PNRIA/output_new_short/patches.h5
  learning_mode: conservative
  data_augmentation: noise 
  normalization_mode: test
  toEncode: ['positions']
  stride: 3
validset:
  type: KFoldsFilamentsDataset
  dataset_path: /mnt/data/WORK/BigSF/Toolbox/PNRIA/output_new_short/patches.h5
  learning_mode: conservative
  data_augmentation: noise 
  normalization_mode: test
  toEncode: ['positions']
  stride: 1
testset:
  type: KFoldsFilamentsDataset
  dataset_path: /mnt/data/WORK/BigSF/Toolbox/PNRIA/output_new_short/patches.h5
  learning_mode: conservative
  data_augmentation: noise 
  normalization_mode: test
  toEncode: ['positions']
  stride: 1
  