model:
  type: unet
  name: unet2D_pe_alt
  in_channels: 1
  out_channels: 1
  features: 64
  dimension: 2
  num_blocks: 4
  encoder_pos: before
  encoder:
    type : Identity
optimizer:
  type: Adam
  lr: 0.0005
  betas: [0.9, 0.99]
scheduler:
  type: OneCycleLR
  max_lr: 0.0005
  epochs: 100
  anneal_strategy: "cos"
  pct_start: 0.1
dataset:
  type: FilamentsDataset
  dataset_path: /home/cloud-user/work/data_bigsf/PNRIA/output_old/fold_0_train.h5
  learning_mode: conservative
  data_augmentation: noise
  normalization_mode: test
  missingmap: True
  input_data_noise: 1
  output_data_noise: 1
  toEncode: ['positions']




# PNRIA/torch_c/models_c/unet_pe_alt.yml