dataset:
  type: FilamentsDataset
  dataset_path: /home/cloud-user/work/data_bigsf/PNRIA/output_test_preprocessing2fold_0_test.h5
  learning_mode: conservative
  data_augmentation: noise 
  normalization_mode: test
  missingmap: True
  input_data_noise: 1
  output_data_noise: 1
  toEncode: ['positions']