model:
  type: unet
  name: unet2D_pe_alt
  in_channels: 1
  out_channels: 1
  features: 64
  dim: 2
  num_blocks: 4
optimizer:
  type: Adam
  lr: 0.0005
  betas: [0.9, 0.99]
scheduler:
  type: OneCycleLR
  max_lr: 0.0005
  epochs: 100
  anneal_strategy: "cos"
  pct_start: 0.1




# PNRIA/torch_c/models_c/unet_pe_alt.yml