output_dir: ./
run_name: run
epoch: 15
split_ratio: 0.8
model:
  type: unet
  name: unet2D_pe_alt
  in_channels: 1
  out_channels: 1
  features: 64
  dimension: 2
  num_blocks: 5
optimizer:
  type: Adam
  lr: 0.005
scheduler:
  type: MultiStepLR
  milestones: [ 10, 20, 30, 40, 50, 60, 70, 80, 90 ]
  gamma: 0.1
train_dataset:
  type: FilamentsDataset
  #  dataset_path: /mnt/data/WORK/BigSF/data/cross_val_datasets/train/fold_0_train.h5
  dataset_path: /mnt/data/WORK/BigSF/data/minidatav1/fold_0_train.h5
  normalization_mode: test
val_dataset:
  type: FilamentsDataset
  #  dataset_path: /mnt/data/WORK/BigSF/data/cross_val_datasets/train/fold_0_train.h5
  dataset_path: /mnt/data/WORK/BigSF/data/minidatav1/fold_0_train.h5
  normalization_mode: test
#