output_dir: /lustre/fsn1/projects/rech/zbz/commun/old_data/
run_name: run_old_data
epoch: 15
num_workers: 20
model:
  type: unet
  name: unet2D_pe_alt
  in_channels: 1
  out_channels: 1
  features: 64
  dimension: 2
  num_blocks: 5
  encoder: /lustre/fswork/projects/rech/zbz/udg82mu/Toolbox/configs/encoder/encoderLin.yml
  encoder_cat_position: middle
optimizer:
  type: Adam
  lr: 0.005
scheduler:
  type: MultiStepLR
  milestones: [ 10, 20, 30, 40, 50, 60, 70, 80, 90 ]
  gamma: 0.1
train_dataset:
  type: FilamentsDataset
  name: train
  dataset_path: /lustre/fsn1/projects/rech/zbz/commun/bigdata/fold_0_train.h5
  normalization: direct
  data_augmentations:
    - type: ToTensor
    - type: RandomRotation
      degrees: 180
      keys_to_augment: ["patch", "spines", "labelled"]
  toEncode: ['positions']
  stride: 8
val_dataset:
  type: FilamentsDataset
  name: valid
  dataset_path: /lustre/fsn1/projects/rech/zbz/commun/bigdata/fold_0_validation.h5
  normalization: direct
  data_augmentations:
    - type: ToTensor
    - type: RandomRotation
      degrees: 180
      keys_to_augment: ["patch", "spines", "labelled"]
  toEncode: ['positions']
  stride: 8
test_dataset:
  name: test
  type: FilamentsDataset
  dataset_path: /lustre/fsn1/projects/rech/zbz/commun/bigdata/fold_0_test.h5
  normalization: direct
  data_augmentations:
    - type: ToTensor
    - type: RandomRotation
      degrees: 180
      keys_to_augment: ["patch", "spines", "labelled"]
  toEncode: ['positions']
  stride: 8
