type: LinPositionEncoding
vars_config: [
  {
    "index": 1,
    "expand_dims": 32,
    "scale": 114000.,
    "offset": 0.00319444444400,
    "unsqueeze": True,
    "angle": 180.0
  },
  {
    "index": 0,
    "expand_dims": 32,
    "scale": 1800.,
    "offset": 0.00319444444400,
    "unsqueeze": True,
    "angle": 180.0
  }
]